services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - somenetwork
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discogs-database
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - somenetwork

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - ./backend/.env
    networks:
      - somenetwork
    depends_on:
      - db
networks:
  somenetwork:
    driver: bridge

volumes:
  postgres_data: